---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: deployment/stages/dev/mysql
    repoURL: 'https://github.com/deadpoet6/demo.git'
    targetRevision: HEAD
  project: default
---
## wordpress
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: deployment/stages/dev/wordpress
    repoURL: 'https://github.com/deadpoet6/demo.git'
    targetRevision: HEAD
  project: default