---
bases:
- ../../../base/wordpress/

resources:
- ./service.yaml

patchesStrategicMerge:
- deployment.yaml

vars:
- name: WORDPRESS_SERVICE
  objref:
    kind: Service
    name: wordpress-dev
    apiVersion: v1
